@startuml
component Common {
    package Common {

        package services {
            interface IActor {
                speed
                move()
                placeWeapon(IWeapon)
            }

            interface IWeapon {
                damagePoints
            }

            interface IDamageable {
                hitPoints
            }

            interface IGamePluginService {
                start()
                stop()
            }

            interface IEntityProcessingService {
                process()
            }

            interface IPostEntityProcessingService {
                process()
            }
        }

        package data {
            class World {
                entities
                addEntity()
                removeEntity()
                getEntity()
            }

            class Entity {
                coordinates
                direction

                getCoordinates()
                setCoordinates(coordinates)
                getDirection()
                setDirection(direction)
            }
        }
    }


'	component Parts {
'		interface EntityPart {
'			process()
'		}
'
'		class LifePart implements EntityPart {
'		}
'
'		class MovingPart implements EntityPart {
'		}
'
'		class PositionPart implements EntityPart {
'		}
'
'	}
}
component Bomb{
    package BombSystem {
        class Bomb implements Common.Common.services.IWeapon{
            - timeOfPlacement: Long
            - timeTillExplosion: Long
            - damagePoints: int
            - blastArea: Collections
            + setBlastArea(Collections)
            + calcTimeTillExplosion()
        }
        Bomb --|> Entity : inherits

        class BombExplosionSystem implements Common.Common.services.IEntityProcessingService {
            - world: World
            - gameData: GameData
            + BombExplosionSystem(GameData, World)
            + calculateBlastArea(Bomb, World)
            + process()
        }
    }
}

component Player {
    class Player {
    }

    class PlayerControlSystem {
    - IWeapon[] placeableWeapons
    + placeWeapon()
    + takeDamage()
    + process()
    }

    class PlayerPlugin {
    - Entity playerEntity
    + createPlayer()
    + start()
    + stop()
    }

    Common.Common.services.IActor <|.. Player.PlayerControlSystem
    Common.Common.services.IDamageable <|.. Player.PlayerControlSystem
    Common.Common.data.Entity <|-- Player.Player
    Common.Common.services.IEntityProcessingService <|.. Player.PlayerControlSystem
    Common.Common.services.IGamePluginService <|.. Player.PlayerPlugin
}



@enduml