@startuml
component Common {
    package Common {

        package services {
            interface IActor {
                speed
                move()
                placeWeapon(IWeapon)
            }

            interface IWeapon {
                getDamagePoints()
                setDamagePoints()
            }

            interface ICollidable {
                getCollidable()
                setCollidable()
            }

            interface IDamageable {
                getHitPoints()
                setHitPoints()
            }

            interface IGamePluginService {
                start()
                stop()
            }
            interface IMap {
                getWidth()
                getHeight()
                }

            interface IEntityProcessingService {
                process()
            }

            interface IPostEntityProcessingService {
                postProcess()
            }
        }

        package data {
            class World {
                entities
                map
                addEntity()
                removeEntity()
                getEntity()
                getMap()
            }


            class Entity {
                coordinates
                direction

                getCoordinates()
                setCoordinates(coordinates)
                getDirection()
                setDirection(direction)
            }
            class Map {
                - width: int
                - height: int
                - map: Grid
                + getMap(): Grid
                + setMap(Grid)
                + updateTile(coord, value)
                + isMoveAllowed(Entity, newCoordinates): boolean
                - isTileOccupied(coord): boolean
                }


        }
    }
    note left of Map: Grid is a map of coordinates and booleans to represent obstacles


'	component Parts {
'		interface EntityPart {
'			process()
'		}
'
'		class LifePart implements EntityPart {
'		}
'
'		class MovingPart implements EntityPart {
'		}
'
'		class PositionPart implements EntityPart {
'		}
'
'	}
}
component Bomb{
    package BombSystem {
        class Bomb implements Common.Common.services.IWeapon{
            - timeOfPlacement: Long
            - timeTillExplosion: Long
            - damagePoints: int
            - blastArea: Collections<Coordinates>
            + setBlastArea(Collections<Coordinates>)
            + calcTimeTillExplosion()
        }
        Bomb --|> Entity : inherits

        class BombExplosionSystem implements Common.Common.services.IEntityProcessingService {
            - world: World
            + BombExplosionSystem(World)
            + calculateBlastArea(Bomb, World)
            + process()
        }
    }
}

component Enemy{
    class enemyControlSystem{
        placeBomb()
        move()
    }
    component AI{
    'maybe an interface
        class PathFinding{
            calculatePathToPlayer(Player)
        }

        class BombPlacing {
            calculateOptimalPlacement(Entity, Bomb))
        }
    }

    class EnemyCollisionControlSystem{
        XCord  'maybe?
        YCord  'maybe?
    }
}

component Player {
    class Player {
    }

    class PlayerControlSystem {
    - IWeapon[] placeableWeapons
    + placeWeapon()
    + takeDamage()
    + process()
    }

    class PlayerPlugin {
    - Entity playerEntity
    + createPlayer()
    + start()
    + stop()
    }

    Common.Common.services.IActor <|.. Player.PlayerControlSystem
    Common.Common.services.IDamageable <|.. Player.PlayerControlSystem
    Common.Common.data.Entity <|-- Player.Player
    Common.Common.services.IEntityProcessingService <|.. Player.PlayerControlSystem
    Common.Common.services.IGamePluginService <|.. Player.PlayerPlugin
}



@enduml